name: Verify Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  verify-build:
    name: Verify Build
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup CMake
        uses: lukka/get-cmake@latest

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug ..

      - name: Build
        run: |
          cd build
          cmake --build . --config Debug